version: '3'
services:
  database: # service name, change to whatever you want 
    image: mongo:latest # must be mongo 
    container_name: 'mongo-container' # give container a name, can be optional 
    env_file:
      - ./.env 
    ports:
      - 27017:27017
    volumes: 
      - ./mongo-volume:/data/db # define file/folder that you want to use for container 

volumes:  
  mongo-volume:

