name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: { go-version: '1.13' }
    - name: Run vetters
      run: |
        cd backend/
        make lint  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Build
      run: |
        cd backend/
        make build
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      database: 
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          - 27017:27017
        volumes:
          - mongo:/data/db
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: |
        cd backend/
        make test
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29

          # Optional: working directory, useful for monorepos
        working-directory: backend

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
